# Generated by Django 2.1 on 2019-12-30 09:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, lowercase=True, unique=True)),
                ('subject', models.CharField(max_length=128)),
                ('body', models.TextField(max_length=5000)),
                ('recipient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='core.UserProfile')),
                ('referenced_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Post')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
