# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20170209_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfeedpage',
            name='category',
            field=models.CharField(choices=[('foia', 'foia'), ('strategy_budget_performance', 'strategy budget performance'), ('agency_operations', 'agency operations'), ('privacy', 'privacy'), ('procurement_contracting_reports', 'procurement contracting reports'), ('annual_anniversary', 'annual anniversary'), ('oig', 'oig')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='category',
            field=models.CharField(choices=[('annual report', 'Annual report'), ('request for proposal (rfp)', 'Request for proposal (RFP)'), ('anniversary report', 'Anniversary report'), ('purchase inventory', 'Purchase inventory'), ('strategic plan', 'Strategic plan'), ('privacy act notices', 'Privacy Act notices'), ('operation plan', 'Operation plan'), ('semiannual report', 'Semiannual report'), ('congressional budget justification', 'Congressional budget justification'), ('annual performance report', 'Annual performance report'), ('special review report', 'Special review report'), ('it strategic plan', 'IT strategic plan'), ('performance and accountability report', 'Performance and accountability report'), ('audit report', 'Audit report'), ('fair act inventory report', 'FAIR Act inventory report'), ('inspection report', 'Inspection report'), ('shutdown plan', 'Shutdown plan'), ('annual foia report', 'Annual FOIA report'), ('privacy policy', 'Privacy policy')], max_length=255, null=True),
        ),
    ]
