# Generated by Django 2.1 on 2019-09-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user_media.models.get_image_file_path, verbose_name='Image')),
                ('thumb_x', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail x')),
                ('thumb_x2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail x2')),
                ('thumb_y', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail y')),
                ('thumb_y2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail y2')),
                ('thumb_w', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail width')),
                ('thumb_h', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thumbnail height')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
