# Generated by Django 2.1 on 2019-12-30 09:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, lowercase=True, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4)),
                ('body', models.TextField(max_length=5000)),
                ('reviewee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='core.UserProfile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='core.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, lowercase=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='core.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
